### ISSUE TITLE
Docker submit error

### ISSUE THREAD

**Issue by beandkay** [pengmun/splid-devkit#2]
I have followed the instructions from README for the **ml_baseline** submission; however, the submission always shows me the **failed** status. Could you confirm that the instruction is correct?

**Comment by vrodriguezf** [comment]
Hi, thank you for your interest in the challenge! We tried to submit a test submission today too and it did not work either. We already contact EvalAI to try fixing this asap. We'll let you know once the submission service is restored.

Best!

**Comment by beandkay** [comment]
have you resolve the problem yet?

**Comment by vrodriguezf** [comment]
Not yet, we are still in touch with EvalAI to solve it. Keep an eye on this forum thread, we will notify there once the issue is solved:
https://evalai-forum.cloudcv.org/t/we-are-fixing-the-submission-server/1757

**Comment by vrodriguezf** [comment]
Hi,

Please see [this thread](https://evalai-forum.cloudcv.org/t/we-are-fixing-the-submission-server/1757/2) for an update on this issue.

Best!
Víctor

**Comment by beandkay** [comment]
Hi,

I tried to resubmit again with the modification from this repo.
The output is still failing in my case, with the output log as follows:
```Saved predictions to: /submission/test_predictions.csv```

Based on this observation, the code ran fine, but there is still something that happens after that...
I use the ml approach, not the heuristic one (as I saw the heuristic results on the leaderboard)

**Comment by beandkay** [comment]
Nevermind, I found the problem.
Please correct the sample file to output the ```/submission/submission.csv``` file instead of ```/submission/test_predictions.csv```

**Comment by vrodriguezf** [comment]
It was already updated, make sure you pull the last version of the repo!
